//! @generated by speet-abi-codegen — DO NOT EDIT
//! Source: test-data/abi-spec/libc-minimal.bridgesupport.xml
//! Symbols: exit, printf, write
//! Architectures: x86_64, aarch64
//! Mode: all symbols (libc/libSystem baseline)

pub mod exit;
pub mod printf;
pub mod write;
pub mod registry;

