//! @generated by speet-abi-codegen — DO NOT EDIT
//! Source: test-data/abi-spec/libc-minimal.bridgesupport.xml
//! Symbols: exit, printf, write

use binary_io::BinArch;
use os_abi_spec::CallingConvention;

pub const STUB_SYMBOLS: &[&str] = &["exit", "printf", "write"];

/// Whether a checked-in redirect stub exists for `symbol` (after `_` stripping).
pub fn has_stub(symbol: &str) -> bool {
    let bare = symbol.strip_prefix('_').unwrap_or(symbol);
    STUB_SYMBOLS.contains(&bare)
}

pub fn calling_convention(arch: BinArch, symbol: &str) -> Option<CallingConvention> {
    let bare = symbol.strip_prefix('_').unwrap_or(symbol);
    match bare {
        "exit" => super::exit::calling_convention(arch),
        "printf" => super::printf::calling_convention(arch),
        "write" => super::write::calling_convention(arch),
        _ => None,
    }
}

pub fn pointer_arg_indices(symbol: &str) -> Option<&'static [usize]> {
    let bare = symbol.strip_prefix('_').unwrap_or(symbol);
    match bare {
        "exit" => Some(super::exit::POINTER_ARG_INDICES),
        "printf" => Some(super::printf::POINTER_ARG_INDICES),
        "write" => Some(super::write::POINTER_ARG_INDICES),
        _ => None,
    }
}

pub fn fn_ptr_arg_indices(symbol: &str) -> Option<&'static [usize]> {
    let bare = symbol.strip_prefix('_').unwrap_or(symbol);
    match bare {
        "exit" => Some(super::exit::FN_PTR_ARG_INDICES),
        "printf" => Some(super::printf::FN_PTR_ARG_INDICES),
        "write" => Some(super::write::FN_PTR_ARG_INDICES),
        _ => None,
    }
}

/// Whether `symbol` has fn-ptr parameters rewritten via the guest stub catalog.
pub fn requires_fn_ptr_rewrite(symbol: &str) -> bool {
    fn_ptr_arg_indices(symbol).is_some_and(|idx| !idx.is_empty())
}
