//! Checked-in ABI redirect stub registry (generated by `os-abi-codegen`).

mod generated;

use binary_io::BinArch;
use os_abi_spec::{AbiSpec, CallingConvention};
use os_host_api::{FuncImport, ImportManifest, WasmValType};

pub mod emit;

pub use generated::registry::{
    calling_convention, fn_ptr_arg_indices, has_stub, pointer_arg_indices,
    requires_fn_ptr_rewrite, STUB_SYMBOLS,
};

/// Phase 1 helper: derive [`ImportManifest`] intercept metadata for
/// symbols declared in `spec`. Only symbols with simple scalar/pointer
/// signatures and no function-pointer args become tunnel imports today;
/// fn-ptr symbols are omitted unless a checked-in redirect stub exists.
///
/// `base` supplies the always-present syscall/hint imports shared by every
/// thin-runtime module; spec-derived imports are appended after it.
pub fn extend_manifest(
    base: &ImportManifest,
    spec: &AbiSpec,
    symbols: &[&str],
) -> ImportManifest {
    let mut m = base.clone();
    for &sym in symbols {
        let Some(f) = spec.lookup(sym) else {
            continue;
        };
        if spec.accepts_function_pointers(sym) && !has_stub(sym) {
            continue;
        }
        if m.func_imports.iter().any(|imp| {
            imp.intercepts.iter().any(|s| s == sym || s.strip_prefix('_') == Some(sym))
        }) {
            continue;
        }
        let (params, results) = bridgesupport_wasm_types(f);
        m.func_imports.push(FuncImport {
            module: "env".into(),
            name: sym.to_string(),
            params,
            results,
            intercepts: intercept_names(sym),
        });
    }
    m
}

fn intercept_names(sym: &str) -> Vec<String> {
    let mut out = vec![sym.to_string()];
    if !sym.starts_with('_') {
        out.push(format!("_{sym}"));
    }
    out
}

fn bridgesupport_wasm_types(f: &os_abi_spec::AbiFunction) -> (Vec<WasmValType>, Vec<WasmValType>) {
    use WasmValType::{I32, I64};
    let params = f
        .args
        .iter()
        .map(|a| match a.bridgesupport_type.as_deref() {
            Some("q" | "Q" | "d" | "D") => I64,
            _ => I32,
        })
        .collect();
    let results = if f.retval.kind == os_abi_spec::AbiValueKind::Void {
        vec![]
    } else {
        vec![match f.retval.bridgesupport_type.as_deref() {
            Some("q" | "Q" | "d" | "D") => I64,
            _ => I32,
        }]
    };
    (params, results)
}

/// PLT-hook marshalling: checked-in stub first, then [`ImportManifest`] WASM
/// param types for the intercept slot (e.g. `execve` → `__speet_execve`).
pub fn plt_calling_convention(
    manifest: &ImportManifest,
    arch: BinArch,
    guest_symbol: &str,
) -> CallingConvention {
    if let Some(cc) = calling_convention(arch, guest_symbol) {
        return cc;
    }
    hook_calling_convention_from_manifest(manifest, arch, guest_symbol)
        .unwrap_or_default()
}

fn hook_calling_convention_from_manifest(
    manifest: &ImportManifest,
    arch: BinArch,
    guest_symbol: &str,
) -> Option<CallingConvention> {
    let (_, import_name) = manifest.resolve_intercept(guest_symbol)?;
    let imp = manifest
        .func_imports
        .iter()
        .find(|i| i.name == import_name)?;
    Some(import_to_calling_convention(arch, imp))
}

fn import_to_calling_convention(arch: BinArch, imp: &FuncImport) -> CallingConvention {
    let arg_locals = match arch {
        BinArch::X86_64 => x86_64_arg_locals(imp.params.len()),
        BinArch::AArch64 => (0..imp.params.len() as u32).collect(),
    };
    let arg_wrap_i32 = imp
        .params
        .iter()
        .map(|t| matches!(t, WasmValType::I32))
        .collect();
    let (result_local, result_extend_i32) = match imp.results.first() {
        None => (None, false),
        Some(WasmValType::I32) => (Some(0), true),
        Some(_) => (Some(0), false),
    };
    CallingConvention {
        arg_locals,
        arg_wrap_i32,
        result_local,
        result_extend_i32,
    }
}

fn x86_64_arg_locals(n: usize) -> Vec<u32> {
    const ORDER: [u32; 6] = [7, 6, 2, 3, 8, 9]; // RDI, RSI, RDX, RCX, R8, R9
    ORDER.iter().take(n).copied().collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"<?xml version="1.0"?>
<signatures version="1.0">
  <function name="write">
    <arg type="i"/>
    <arg type="^v"/>
    <arg type="Q"/>
    <retval type="q"/>
  </function>
  <function name="printf">
    <arg type="*"/>
    <arg type="^?"/>
    <retval type="i"/>
  </function>
  <function name="exit">
    <arg type="i"/>
    <retval type="v"/>
  </function>
</signatures>"#;

    #[test]
    fn write_stub_registered() {
        assert!(has_stub("write"));
        assert!(has_stub("_write"));
        assert!(has_stub("printf"));
        assert_eq!(STUB_SYMBOLS, &["write", "exit", "printf"]);
        let cc = calling_convention(BinArch::X86_64, "write").unwrap();
        assert_eq!(cc.arg_locals, vec![7, 6, 2]);
        assert_eq!(pointer_arg_indices("write"), Some([1].as_slice()));
        assert_eq!(fn_ptr_arg_indices("printf"), Some([1].as_slice()));
        assert!(requires_fn_ptr_rewrite("printf"));
        assert!(!requires_fn_ptr_rewrite("write"));
    }

    #[test]
    fn execve_from_integrated_manifest() {
        let m = ImportManifest::integrated_native();
        let cc = plt_calling_convention(&m, BinArch::X86_64, "execve");
        assert_eq!(cc.arg_locals, vec![7, 6, 2]);
        assert_eq!(cc.arg_wrap_i32, vec![false, false, false]);
        assert_eq!(cc.result_local, Some(0));
        assert!(cc.result_extend_i32);
    }

    #[test]
    fn extend_manifest_includes_fn_ptr_symbols_with_stub() {
        let spec = os_abi_spec::parse_bridgesupport(SAMPLE).unwrap();
        let base = ImportManifest::native_syscall();
        let extended = extend_manifest(&base, &spec, &["write", "printf", "exit"]);

        assert!(extended.index_of("env", "write").is_some());
        assert!(extended.index_of("env", "exit").is_some());
        assert!(extended.index_of("env", "printf").is_some());
    }
}
